"""add theme_preferences to accounts

Revision ID: 580c730a890f
Revises: eef39c9e1f7c
Create Date: 2026-06-27 08:36:01.018702
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '580c730a890f'
down_revision: Union[str, None] = 'eef39c9e1f7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('theme_preferences', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'theme_preferences')
    # ### end Alembic commands ###
