"""add patients table

Revision ID: aeaa48b0bb45
Revises: a368ae712521
Create Date: 2026-06-25 19:49:16.705525
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'aeaa48b0bb45'
down_revision: Union[str, None] = 'a368ae712521'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('medical_id', sa.Text(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.Text(), nullable=False),
    sa.Column('relationship_to_account', sa.Text(), nullable=False),
    sa.Column('has_cnic', sa.Boolean(), nullable=False),
    sa.Column('guardian_patient_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['guardian_patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_account_id'), 'patients', ['account_id'], unique=False)
    op.create_index(op.f('ix_patients_medical_id'), 'patients', ['medical_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patients_medical_id'), table_name='patients')
    op.drop_index(op.f('ix_patients_account_id'), table_name='patients')
    op.drop_table('patients')
    # ### end Alembic commands ###
