"""add observation_types and lifestyle_observations tables

Revision ID: c8a6af86a80b
Revises: fe54451c94dc
Create Date: 2026-06-25 21:02:51.142693
"""
import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c8a6af86a80b'
down_revision: Union[str, None] = 'fe54451c94dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('observation_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('display_label', sa.Text(), nullable=False),
    sa.Column('loinc_code', sa.Text(), nullable=True),
    sa.Column('value_type', sa.Text(), nullable=False),
    sa.Column('unit', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('lifestyle_observations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('observation_type_id', sa.UUID(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('value_numeric', sa.Numeric(), nullable=True),
    sa.Column('value_code', sa.Text(), nullable=True),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('unit', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['observation_type_id'], ['observation_types.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_lifestyle_obs_patient_type_date', 'lifestyle_observations', ['patient_id', 'observation_type_id', 'effective_date'], unique=False)
    op.create_index(op.f('ix_lifestyle_observations_account_id'), 'lifestyle_observations', ['account_id'], unique=False)
    op.create_index(op.f('ix_lifestyle_observations_effective_date'), 'lifestyle_observations', ['effective_date'], unique=False)
    op.create_index(op.f('ix_lifestyle_observations_patient_id'), 'lifestyle_observations', ['patient_id'], unique=False)
    # ### end Alembic commands ###

    # Seed observation types (LOINC codes verified against loinc.org).
    obs_table = sa.table(
        "observation_types",
        sa.column("id", sa.UUID),
        sa.column("key", sa.Text),
        sa.column("display_label", sa.Text),
        sa.column("loinc_code", sa.Text),
        sa.column("value_type", sa.Text),
        sa.column("unit", sa.Text),
        sa.column("is_active", sa.Boolean),
    )
    op.bulk_insert(obs_table, [
        {"id": str(uuid.uuid4()), "key": "smoking_status", "display_label": "Smoking Status", "loinc_code": "72166-2", "value_type": "coded", "unit": None, "is_active": True},
        {"id": str(uuid.uuid4()), "key": "alcohol_use", "display_label": "Alcohol Use", "loinc_code": "74013-4", "value_type": "coded", "unit": None, "is_active": True},
        {"id": str(uuid.uuid4()), "key": "exercise", "display_label": "Physical Activity", "loinc_code": "89555-7", "value_type": "numeric", "unit": "min/week", "is_active": True},
        {"id": str(uuid.uuid4()), "key": "sleep_duration", "display_label": "Sleep Duration", "loinc_code": "93832-4", "value_type": "numeric", "unit": "h", "is_active": True},
        {"id": str(uuid.uuid4()), "key": "other", "display_label": "Other", "loinc_code": None, "value_type": "text", "unit": None, "is_active": True},
    ])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lifestyle_observations_patient_id'), table_name='lifestyle_observations')
    op.drop_index(op.f('ix_lifestyle_observations_effective_date'), table_name='lifestyle_observations')
    op.drop_index(op.f('ix_lifestyle_observations_account_id'), table_name='lifestyle_observations')
    op.drop_index('ix_lifestyle_obs_patient_type_date', table_name='lifestyle_observations')
    op.drop_table('lifestyle_observations')
    op.drop_table('observation_types')
    # ### end Alembic commands ###
