"""add epi_vaccines immunizations and family_histories tables

Revision ID: fe54451c94dc
Revises: 9d81bd8fc2bd
Create Date: 2026-06-25 20:43:44.103795
"""
import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fe54451c94dc'
down_revision: Union[str, None] = '9d81bd8fc2bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('epi_vaccines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('short_name', sa.Text(), nullable=False),
    sa.Column('total_doses', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('short_name')
    )
    op.create_table('family_histories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('relationship', sa.Text(), nullable=False),
    sa.Column('condition_code_system', sa.Text(), nullable=False),
    sa.Column('condition_code', sa.Text(), nullable=True),
    sa.Column('condition_display_name', sa.Text(), nullable=False),
    sa.Column('onset_age', sa.Integer(), nullable=True),
    sa.Column('deceased', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_family_histories_account_id'), 'family_histories', ['account_id'], unique=False)
    op.create_index(op.f('ix_family_histories_patient_id'), 'family_histories', ['patient_id'], unique=False)
    op.create_table('immunizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('epi_vaccine_id', sa.UUID(), nullable=True),
    sa.Column('vaccine_display_name', sa.Text(), nullable=False),
    sa.Column('code_system', sa.Text(), nullable=True),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('dose_number', sa.Integer(), nullable=True),
    sa.Column('occurrence_date', sa.Date(), nullable=False),
    sa.Column('lot_number', sa.Text(), nullable=True),
    sa.Column('manufacturer', sa.Text(), nullable=True),
    sa.Column('site', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['epi_vaccine_id'], ['epi_vaccines.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_immunizations_account_id'), 'immunizations', ['account_id'], unique=False)
    op.create_index(op.f('ix_immunizations_patient_id'), 'immunizations', ['patient_id'], unique=False)
    # ### end Alembic commands ###

    # Seed Pakistan EPI vaccines (source: Pakistan Expanded Programme on Immunization
    # schedule per WHO Pakistan / NEPI guidelines, current as of 2024).
    epi_table = sa.table(
        "epi_vaccines",
        sa.column("id", sa.UUID),
        sa.column("name", sa.Text),
        sa.column("short_name", sa.Text),
        sa.column("total_doses", sa.Integer),
        sa.column("description", sa.Text),
    )
    op.bulk_insert(epi_table, [
        {"id": str(uuid.uuid4()), "name": "Bacillus Calmette-Guérin", "short_name": "BCG", "total_doses": 1, "description": "Tuberculosis vaccine, given at birth"},
        {"id": str(uuid.uuid4()), "name": "Oral Polio Vaccine", "short_name": "OPV", "total_doses": 4, "description": "OPV-0 at birth, OPV-1/2/3 at 6/10/14 weeks"},
        {"id": str(uuid.uuid4()), "name": "Pentavalent Vaccine", "short_name": "Penta", "total_doses": 3, "description": "DPT + Hep B + Hib, given at 6/10/14 weeks"},
        {"id": str(uuid.uuid4()), "name": "Pneumococcal Conjugate Vaccine", "short_name": "PCV", "total_doses": 3, "description": "PCV-10, given at 6/10/14 weeks"},
        {"id": str(uuid.uuid4()), "name": "Rotavirus Vaccine", "short_name": "Rota", "total_doses": 2, "description": "Given at 6 and 10 weeks"},
        {"id": str(uuid.uuid4()), "name": "Inactivated Polio Vaccine", "short_name": "IPV", "total_doses": 2, "description": "IPV-1 at 14 weeks, IPV-2 at 9 months"},
        {"id": str(uuid.uuid4()), "name": "Measles Vaccine", "short_name": "Measles", "total_doses": 2, "description": "Measles-1 at 9 months, Measles-2 at 15 months"},
        {"id": str(uuid.uuid4()), "name": "Typhoid Conjugate Vaccine", "short_name": "TCV", "total_doses": 1, "description": "Given at 9 months"},
    ])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_immunizations_patient_id'), table_name='immunizations')
    op.drop_index(op.f('ix_immunizations_account_id'), table_name='immunizations')
    op.drop_table('immunizations')
    op.drop_index(op.f('ix_family_histories_patient_id'), table_name='family_histories')
    op.drop_index(op.f('ix_family_histories_account_id'), table_name='family_histories')
    op.drop_table('family_histories')
    op.drop_table('epi_vaccines')
    # ### end Alembic commands ###
